language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install --global yarn
install:
  - yarn install
script:
  - yarn build
  - yarn test
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: build
  on:
    branch: master
